caicolanches/cadastroEmp/urls.py
from django.urls import path
from cadastroEmp.views import IndexTemplateView, EstabelecimentoListView, EstabelecimentoUpdateView, EstabelecimentoCreateView, \
    EstabelecimentoDeleteView

from . import views

app_name = 'cadastroEmp'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),

    path('estabelecimento/cadastrar', EstabelecimentoCreateView.as_view(), name="cadastra_estabelecimento"),

    path('estabelecimentos/', EstabelecimentoListView.as_view(), name="lista_estabelecimentos"),

    path('estabelecimento/<pk>', EstabelecimentoUpdateView.as_view(), name="atualiza_estabelecimento"),

    path('estabelecimento/excluir/<pk>', EstabelecimentoDeleteView.as_view(), name="deleta_estabelecimento"),
]

caicolanches/caicolanches/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('pedidoCli/', include('pedidoCli.urls')),
    path('admin/', admin.site.urls),
    path('cadastroEmp/', include('cadastroEmp.urls')),
]

caicolanches/pedidoCli/urls.py
from django.urls import path
from pedidoCli.views import IndexTemplateView, ClienteListView, ClienteUpdateView, ClienteCreateView, ClienteDeleteView
from pedidoCli.views import ProdutoCreateView, ProdutoDeleteView, ProdutoUpdateView, ProdutoListView

from . import views

app_name = 'pedidoCli'
urlpatterns = [
    path('', IndexTemplateView.as_view(), name="index"),

    path('cliente/cadastrar', ClienteCreateView.as_view(), name="cadastra_cliente"),

    path('clientes/', ClienteListView.as_view(), name="lista_clientes"),

    path('cliente/<pk>', ClienteUpdateView.as_view(), name="atualiza_cliente"),

    path('cliente/excluir/<pk>', ClienteDeleteView.as_view(), name="deleta_cliente"),

##PRODUTO URLS##

    path('produto/cadastrar', ProdutoCreateView.as_view(), name="cadastra_produto"),

    path('produto/excluir/<pk>', ProdutoDeleteView.as_view(), name="deleta_produto"),

    path('produto/<pk>', ProdutoUpdateView.as_view(), name="atualiza_produto"),

    path('produtos/', ProdutoListView.as_view(), name="lista_produtos"),
]

caicolanches/cadastroEmp/models.py
from django.db import models

# Create your models here.
class Estabelecimento(models.Model):
    nomeFrant=models.CharField(max_length=150)
    social=models.CharField(max_length=255)
    cnpj=models.CharField(max_length=11,unique=True)
    fone=models.CharField(max_length=11)
    login=models.CharField(max_length=255)
    password=models.CharField(max_length=255)
    endereco=models.ForeignKey("Endereco", on_delete=models.PROTECT)
    responsavel=models.CharField(max_length=150)

class Endereco(models.Model):
    rua=models.CharField(max_length=100)
    bairro=models.CharField(max_length=100)
    numero=models.CharField(max_length=8)
    cidade=models.CharField(max_length=100)
    estado=models.CharField(max_length=100)
    cep=models.CharField(max_length=8)

    def __str__(self):
        return self.rua

caicolanches/pedidoCli/models.py
from django.db import models

# Create your models here.


class Cliente(models.Model):
    nome = models.CharField(max_length=150, null=False, blank=False)
    cpf = models.CharField(max_length=11, null=False, blank=False, unique=True)
    nascimento = models.CharField(max_length=8, null=False, blank=False)
    fone = models.CharField(max_length=11)
    login = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    #endereco = models.ForeignKey("Endereco", on_delete=models.PROTECT)


class Endereco(models.Model):
    rua = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    numero = models.CharField(max_length=8)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    cep = models.CharField(max_length=8)


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)
    preco = models.CharField (max_length=50)

caicolanches/cadastroEmp/forms.py
from .models import Estabelecimento
from django import forms


class InsereEstabelecimentoForm(forms.ModelForm):

    class Meta:
        # Modelo base
        model = Estabelecimento

        # Campos que estarão no form
        fields = [
            'nomeFrant',
            'social',
            'cnpj',
            'fone',
            'login',
            'password',
            'endereco',
            'responsavel'
        ]

caicolanches/pedidoCli/forms.py
from .models import Cliente, Produto
from django import forms
#from models import *


class InsereClienteForm(forms.ModelForm):

    class Meta:
        # Modelo base
        model = Cliente
        ###password = forms.CharField(widget=forms.PasswordInput)

        # Campos que estarão no form
        fields = [
            'nome',
            'cpf',
            'nascimento',
            'fone',
            'login',
            'password',
        ]
class InsereProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto

        fields = [
            'nome',
            'descricao',
            'preco',
        ]

caicolanches/cadastroEmp/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView

from .forms import InsereEstabelecimentoForm
from .models import Estabelecimento


# Create your views here.
class IndexTemplateView(TemplateView):
    template_name = "cadastroEmp/index.html"


class EstabelecimentoListView(ListView):
    template_name = "cadastroEmp/lista.html"
    model = Estabelecimento
    context_object_name = "estabelecimentos"


class EstabelecimentoCreateView(CreateView):
    template_name = "cadastroEmp/cria.html"
    model = Estabelecimento
    form_class = InsereEstabelecimentoForm
    success_url = reverse_lazy("cadastroEmp:lista_estabelecimentos")


class EstabelecimentoUpdateView(UpdateView):
    template_name = "cadastroEmp/atualiza.html"
    model = Estabelecimento
    fields = '__all__'
    context_object_name = 'estabelecimento'
    success_url = reverse_lazy("cadastroEmp:lista_estabelecimentos")


class EstabelecimentoDeleteView(DeleteView):
    template_name = "cadastroEmp/exclui.html"
    model = Estabelecimento
    context_object_name = 'estabelecimento'
    success_url = reverse_lazy("cadastroEmp:lista_estabelecimentos")

caicolanches/pedidoCli/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from .models import Cliente, Produto
from .forms import InsereClienteForm, InsereProdutoForm


class IndexTemplateView(TemplateView):
    template_name = "pedidoCli/index.html"


class ClienteListView(ListView):
    template_name = "pedidoCli/lista.html"
    model = Cliente
    context_object_name = 'clientes'


class ClienteCreateView(CreateView):
    template_name = "pedidoCli/cria.html"
    model = Cliente
    form_class = InsereClienteForm
    success_url = reverse_lazy("pedidoCli:lista_clientes")


class ClienteUpdateView(UpdateView):
    template_name = "pedidoCli/atualiza.html"
    model = Cliente
    fields = '__all__'
    context_object_name = 'cliente'
    success_url = reverse_lazy("pedidoCli:lista_clientes")


class ClienteDeleteView(DeleteView):
    template_name = "pedidoCli/exclui.html"
    model = Cliente
    context_object_name = 'cliente'
    success_url = reverse_lazy("pedidoCli:lista_clientes")


##PRODUTOS VIEWS##

class ProdutoCreateView(CreateView):
    template_name = "pedidoCli/criapro.html"
    model = Produto
    form_class = InsereProdutoForm
    success_url = reverse_lazy("pedidoCli:lista_produtos")


class ProdutoDeleteView(DeleteView):
    template_name = "pedidoCli/excluipro.html"
    model = Produto
    context_object_name = 'produto'
    success_url = reverse_lazy("pedidoCli:lista_produtos")


class ProdutoUpdateView(UpdateView):
    template_name = "pedidoCli/atualizapro.html"
    model = Produto
    fields = '__all__'
    context_object_name = 'produto'
    success_url = reverse_lazy("pedidoCli:lista_produtos")


class ProdutoListView(ListView):
    template_name = "pedidoCli/listapro.html"
    model = Produto
    context_object_name = 'produtos'

caicolanches/cadastroEmp/templates/cadastroEmp/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Gerenciamento de Estabelecimentos parceiros{% endblock %}</title>

        <!-- Logo -->
        <link rel="shortcut icon" href="{% static 'cadastroEmp/img/logo.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'cadastroEmp/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'cadastroEmp/css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'cadastroEmp:index' %}">
              <img src="{% static 'cadastroEmp/img/logo.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button" 
                data-toggle="collapse" data-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'cadastroEmp:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cadastroEmp:lista_estabelecimentos' %}">Estabelecimentos</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Hora: </b>{% tempo_atual %}</a>
                    </li>
                </ul>
            </div>
        </nav>
        
        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'cadastroEmp/js/jquery.min.js' %}"></script>
        <script src="{% static 'cadastroEmp/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'cadastroEmp/js/scripts.js' %}"></script>
    </body>
</html>

caicolanches/cadastroEmp/templates/cadastroEmp/atualiza.html
{% extends "cadastroEmp/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Estabelecimento{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Estabelecimento</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome Fantasia -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome Fantasia</span>
              </div>
              {% render_field form.nomeFrant class+="form-control" %}
            </div>

            <!-- Razão social -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Razão social</span>
              </div>
              {% render_field form.social class+="form-control" %}
            </div>

            <!-- CNPJ -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CNPJ</span>
              </div>
              {% render_field form.cnpj class+="form-control" %}
            </div>

            <!-- Telefone -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Telefone</span>
              </div>
              {% render_field form.fone class+="form-control" %}
            </div>

            <!-- Login -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Login</span>
              </div>
              {% render_field form.login class+="form-control" %}
            </div>

            <!-- Password -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Password</span>
              </div>
              {% render_field form.password class+="form-control" %}
            </div>

            <!-- Endereço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Endereço</span>
              </div>
              {% render_field form.endereco class+="form-control" %}
            </div>

            <!-- Responsável -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Responsável</span>
              </div>
              {% render_field form.responsavel class+="form-control" %}
            </div>
            <hr />
            <div class="text-right">
              <a href="{% url 'cadastroEmp:lista_estabelecimentos' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

caicolanches/cadastroEmp/templates/cadastroEmp/exclui.html
<!-- Estendemos do template base -->
{% extends "cadastroEmp/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Estabelecimento</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o estabelecimento <b>{{ estabelecimento.nomeFrant }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'cadastroEmp:lista_estabelecimentos' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

caicolanches/cadastroEmp/templates/cadastroEmp/index.html
<!-- Estendemos do template base -->
{% extends "cadastroEmp/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Estabelecimento</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Estabelecimento</code>.
          </p>
          <a href="{% url 'cadastroEmp:cadastra_estabelecimento' %}"
             class="btn btn-primary">
            Novo Estabelecimento
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Estabelecimentos</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Estabelecimentos</code> cadastrados.
          </p>
          <a href="{% url 'cadastroEmp:lista_estabelecimentos' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

caicolanches/cadastroEmp/templates/cadastroEmp/lista.html
{% extends "cadastroEmp/_layouts/base.html" %}

{% block title %}Lista de Estabelecimentos{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Estabelecimento</h5>

          {% if estabelecimentos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Estabelecimentos</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome Fantasia</th>
                <th scope="col">Razão social</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Telefone</th>
                <th scope="col">Login</th>
                <th scope="col">Password</th>
                <th scope="col">Endereço</th>
                <th scope="col">Responsável</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for estabelecimento in estabelecimentos %}
                <tr>
                  <th scope="row">{{ estabelecimento.nomeFrant }}</th>
                  <td>{{ estabelecimento.nomeFrant }}</td>
                  <td>{{ estabelecimento.social }}</td>
                  <td>{{ estabelecimento.cnpj }}</td>
                  <td>{{ estabelecimento.fone }}</td>
                  <td>{{ estabelecimento.login }}</td>
                  <td>{{ estabelecimento.password }}</td>
                  <td>{{ estabelecimento.endereco }}</td>
                  <td>{{ estabelecimento.responsavel }}</td>
                  <td class="text-center">
                    <a href="{% url 'cadastroEmp:atualiza_estabelecimento' pk=estabelecimento.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'cadastroEmp:deleta_estabelecimento' pk=estabelecimento.id %}"
                      class="btn btn-danger">
                      Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Estabelecimento</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'cadastroEmp:cadastra_estabelecimento' %}" class="btn btn-primary">
              Cadastrar Estabelecimento
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

caicolanches/pedidoCli/templates/pedidoCli/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Gerenciamento do Usuário{% endblock %}</title>

        <!-- Logo -->
        <link rel="shortcut icon" href="{% static 'pedidoCli/img/logo.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'pedidoCli/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'pedidoCli/css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'pedidoCli:index' %}">
              <img src="{% static 'pedidoCli/img/logo.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button"
                data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'pedidoCli:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pedidoCli:lista_clientes' %}">Clientes</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Hora: </b>{% tempo_atual %}</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'pedidoCli/js/jquery.min.js' %}"></script>
        <script src="{% static 'pedidoCli/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'pedidoCli/js/scripts.js' %}"></script>
    </body>
</html>

caicolanches/pedidoCli/templates/pedidoCli/exclui.html
<!-- Estendemos do template base -->
{% extends "pedidoCli/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Apagar conta</h5>

        <p class="card-text">
          Você tem certeza que deseja apagar o cliente <b>{{ cliente.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'pedidoCli:lista_clientes' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

caicolanches/pedidoCli/templates/pedidoCli/index.html
<!-- Estendemos do template base -->
{% extends "pedidoCli/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Cliente</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Cliente</code>.
          </p>
          <a href="{% url 'pedidoCli:cadastra_cliente' %}"
             class="btn btn-primary">
            Novo Cliente
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Clientes</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Clientes</code> cadastrados.
          </p>
          <a href="{% url 'pedidoCli:lista_clientes' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
    <!-- Cadastrar produtos a venda-->
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Produtos</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Produto</code>.
          </p>
          <a href="{% url 'pedidoCli:cadastra_produto' %}"
             class="btn btn-primary">
            Novo Produto
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Produtos</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Produtos</code> cadastrados.
          </p>
          <a href="{% url 'pedidoCli:lista_produtos' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

caicolanches/pedidoCli/templates/pedidoCli/lista.html
{% extends "pedidoCli/_layouts/base.html" %}

{% block title %}Lista de Clientes{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Cliente</h5>

          {% if clientes|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Clientes</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">Data de Nascimento</th>
                <th scope="col">Telefone</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for cliente in clientes %}
                <tr>
                  <th scope="row">{{ cliente.nomeFrant }}</th>
                  <td>{{ cliente.nome }}</td>
                  <td>{{ cliente.cpf }}</td>
                  <td>{{ cliente.nascimento }}</td>
                  <td>{{ cliente.fone }}</td>
                  <td class="text-center">
                    <a href="{% url 'pedidoCli:atualiza_cliente' pk=cliente.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'pedidoCli:deleta_cliente' pk=cliente.id %}"
                      class="btn btn-danger">
                      Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Cliente</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'pedidoCli:cadastra_cliente' %}" class="btn btn-primary">
              Cadastrar Cliente
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

caicolanches/pedidoCli/templates/pedidoCli/listapro.html
{% extends "pedidoCli/_layouts/base.html" %}

{% block title %}Lista de Produtos{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Produto</h5>

          {% if produtos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Produtos</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Preço</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for produto in produtos %}
                <tr>
                  <th scope="row">{{ produto.nomeFrant }}</th>
                  <td>{{ produto.nome }}</td>
                  <td>{{ produto.descricao }}</td>
                  <td>{{ produto.preco }}</td>
                  <td class="text-center">
                    <a href="{% url 'pedidoCli:atualiza_produto' pk=produto.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'pedidoCli:deleta_produto' pk=produto.id %}"
                      class="btn btn-danger">
                      Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Produto</code> foi cadastrado.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'pedidoCli:cadastra_produto' %}" class="btn btn-primary">
              Cadastrar Produto
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}